# Generated by Django 4.2.17 on 2025-01-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Проповідник",
                "verbose_name_plural": "Проповідники",
            },
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField(unique=True)),
                ("quote", models.TextField(blank=True, null=True)),
                ("video", models.URLField(blank=True, null=True)),
                ("audio", models.URLField(blank=True, null=True)),
                ("text", models.URLField(blank=True, null=True)),
                (
                    "preacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sermons_index.preacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проповідь",
                "verbose_name_plural": "Проповіді",
                "ordering": ["date"],
            },
        ),
    ]
