# Generated by Django 4.2.17 on 2025-01-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sermons_index", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="agenda",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="quote",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
