# Generated by Django 4.2.17 on 2026-03-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons_index", "0002_sermon_folder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
