# Generated by Django 4.2.17 on 2025-01-24 15:56

from django.db import migrations, models
import sermons_index.services.storage


class Migration(migrations.Migration):
    dependencies = [
        ("sermons_index", "0003_sermon_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="uploadfile",
            field=models.FileField(
                blank=True,
                null=True,
                storage=sermons_index.services.storage.AppBoxStorage(),
                upload_to="",
            ),
        ),
    ]
