services:
  web:
    image: olehandrus/sermons-index:latest
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - BOX_DEVELOPER_TOKEN=${BOX_DEVELOPER_TOKEN}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
