services:
  web:
    image: olehandrus/sermons-index:latest
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
        BOX_DEVELOPER_TOKEN: ${BOX_DEVELOPER_TOKEN}
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./src:/app/src
      - ./manage.py:/app/manage.py
    command: >
      sh -c "poetry run python manage.py migrate --noinput &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock
