# Generated by Django 4.2.17 on 2025-02-11 16:12

from django.db import migrations, models
import django.db.models.deletion
import sermons_index.services.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField(unique=True)),
                ("reference", models.CharField(max_length=100)),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sermons_index.services.storage.AppBoxStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "text",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sermons_index.services.storage.AppBoxStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "agenda",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sermons_index.services.storage.AppBoxStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "preacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sermons_index.preacher",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
