# Generated by Django 4.2.17 on 2025-02-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sermons_index", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="folder_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
